/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "cyCapsense.h"
#include "cyCapsense_Control.h"
#include "cyCapsense_Filter.h"
#include "cyCapsense_Processing.h"
#include "cyCapsense_Sensing.h"
#include "cyCapsense_Structure.h"
#include "cyCapsense_Tuner.h"
#include "cyCapsense_Configuration.h"
#include "cyCapsense_SensingCSD_LL.h"
#include "cyCapsense_RegisterMap.h"
#include "cyCapsense_SmartSense_LL.h"
#include "cyLed_p43.h"
#include "cyLed_p43_aliases.h"
#include "cyLed_p44.h"
#include "cyLed_p44_aliases.h"
#include "cyLed_p45.h"
#include "cyLed_p45_aliases.h"
#include "cyUart_p50_p51.h"
#include "cyUart_p50_p51_SPI_UART.h"
#include "cyUart_p50_p51_PINS.h"
#include "cyUart_p50_p51_SPI_UART_PVT.h"
#include "cyUart_p50_p51_PVT.h"
#include "cyUart_p50_p51_BOOT.h"
#include "cyBuzzerPWM.h"
#include "Clock_1.h"
#include "cyBuzzer_p55.h"
#include "cyBuzzer_p55_aliases.h"
#include "cySegA_p20.h"
#include "cySegA_p20_aliases.h"
#include "cySegB_p21.h"
#include "cySegB_p21_aliases.h"
#include "cySegC_p22.h"
#include "cySegC_p22_aliases.h"
#include "cySegD_p23.h"
#include "cySegD_p23_aliases.h"
#include "cySegE_p24.h"
#include "cySegE_p24_aliases.h"
#include "cySegF_p25.h"
#include "cySegF_p25_aliases.h"
#include "cySegG_p26.h"
#include "cySegG_p26_aliases.h"
#include "cyDigit1_p34.h"
#include "cyDigit1_p34_aliases.h"
#include "cyDigit2_p35.h"
#include "cyDigit2_p35_aliases.h"
#include "cyCol1_p03.h"
#include "cyCol1_p03_aliases.h"
#include "cyCol2_p02.h"
#include "cyCol2_p02_aliases.h"
#include "cyCol3_p01.h"
#include "cyCol3_p01_aliases.h"
#include "cyCol4_p00.h"
#include "cyCol4_p00_aliases.h"
#include "cyCapsense_ISR.h"
#include "cyUart_p50_p51_SCBCLK.h"
#include "cyUart_p50_p51_tx.h"
#include "cyUart_p50_p51_tx_aliases.h"
#include "cyUart_p50_p51_SCB_IRQ.h"
#include "cyUart_p50_p51_rx.h"
#include "cyUart_p50_p51_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

